"""empty message

Revision ID: d25853df61c1
Revises: a8f9e6bb81b7
Create Date: 2023-05-17 15:18:48.285510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d25853df61c1"
down_revision = "a8f9e6bb81b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("descriptiton", sa.String(length=80), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_column("descriptiton")

    # ### end Alembic commands ###
